### ISSUE TITLE
[Bug] Hosted inference API widget text sometimes not readable

### ISSUE THREAD

**Issue by tomaarsen** [huggingface/hub-docs#764]
Hello!

## Bug overview
* The text in a token classification inference API widget is not visible if the label is indigo and dark mode is active.

## Details
![image](https://user-images.githubusercontent.com/37621491/235911958-898b3923-c66f-4be6-90de-e16b2c712b86.png)

For the website, the following CSS rule is causing light indigo texts to be displayed on top of the same colored light indigo background:
```css
:is(.dark .dark\:text-indigo-100) {
 --tw-text-opacity:1;
 color:rgb(224 231 255/var(--tw-text-opacity));
}
```

## How to reproduce
1. Go to https://huggingface.co/tomaarsen/span-marker-bert-tiny-fewnerd-coarse-super?text=Amelia+Earhart+flew+her+single+engine+Lockheed+Vega+5B+across+the+Atlantic+to+Paris.
2. Use dark mode.
3. Observe the Hosted inference API widget.

## Potential fix
I believe that this rule should simply be removed, allowing this other existing rule to take priority:
```css
.text-indigo-800 {
 --tw-text-opacity:1;
 color:rgb(55 48 163/var(--tw-text-opacity))
}
```
When the first css rule is removed, the text becomes:
![image](https://user-images.githubusercontent.com/37621491/235912035-4cad2be3-8020-4887-b238-5553ab4192c9.png)

That said, I'll let the frontend wizards fight out what the correct fix is.

- Tom Aarsen
