### ISSUE TITLE
[hacktoberfest] Dataset `languages` challenge

### ISSUE THREAD

**Issue by Wauplin** [huggingface/hub-docs#986]
Issue to keep track of the "Dataset `languages` challenge" for the Hacktoberfest 2023.

## Context

The Hugging Face Hub hosts hundreds of thousands of public models and datasets. These datasets and models cover a wide range of languages. One of the main ways in which it's possible to know what language a dataset is in is by looking at the `language` field in the dataset's [metadata](https://huggingface.co/docs/hub/datasets-cards#dataset-card-metadata)  section of the dataset card. 

```yaml
language: 
- "List of ISO 639-1 code for your language"
- lang1
pretty_name: "Pretty Name of the Dataset"
tags:
- tag1
- tag2
license: "any valid license identifier"
task_categories:
- task1
```

Having this field filled in is essential for users to find datasets in their language and give a better idea of the languages that the Hub covers. However, the dataset's author has only sometimes filled this field. This challenge is to fill in the `language` field for datasets that don't have it filled in.

## Instructions

[Check out the instructions details here.](https://github.com/huggingface/hub-docs/blob/main/hacktoberfest_challenges/datasets_without_language.md)

Feel free to ping @davanstrien or @Wauplin for any question or review.
